---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springweb
  labels:
    app: springweb
spec:
  selector:
    matchLabels:
      app: springweb
  template:
    metadata:
      labels:
        app: springweb
    spec:
      containers:
        - name: springweb
          image: sumanth17121988/petclinic:tagversion
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springweb-service
  namespace: default
  labels:
    app: springweb
spec:
  type: NodePort
  selector:
    app: springweb
  ports:
    - port: 9090            # The port exposed internally within the cluster
      targetPort: 8080      # The container port
      nodePort: 32090       # Optional: can be auto-assigned if omitted (range: 30000–32767)
      protocol: TCP

